### ISSUE TITLE
Works with nginx/1.14.0 (Ubuntu)?

### ISSUE THREAD

**Issue by pet21221** [openresty/array-var-nginx-module#6]
Hello,

works this module with nginx version: nginx/1.14.0 (Ubuntu)?
And what is the best way for install this module at 1.14.0?

**Comment by pet21221** [comment]
If i run "./configure --add-dynamic-module=/opt/source/array-var-nginx-module/"
I get the message: "error: ngx_devel_kit is required to build ngx_array_var; please put it before ngx_array_var. "

**Comment by agentzh** [comment]
@pet21221 Read the documentation:

https://github.com/openresty/array-var-nginx-module#installation

And the error message clearly indicates your mistake.

**Comment by agentzh** [comment]
@pet21221 OK, I just noted that the official installation documentation fails to mention the dependency module, ngx_devel_kit, just updated the docs. Thanks for bringing this issue to my attention!

BTW, the latest officially supported nginx target of this module is 1.13.6. Nginx 1.14.0 is not officially tested yet and you are at your own risk when using it (but you are welcome to report any incompatibility issues). And as the documentation states, it's always recommended to use the OpenResty releases so that compatibility is well tested and guaranteed.

**Comment by pet21221** [comment]
Thank you. Now i test it with ngx_devel_kit and i the configure is success. The ngx_http_array_var_module.so file will create. I create a file on my installed nginx webserver on /etc/nginx/modules-enabled/51-mod-http-array-var-module.conf. 

My configure is this:
./configure --prefix=/opt/source/nginx --add-module=/opt/source/nginx/ngx_devel_kit --add-dynamic-module=/opt/source/nginx/array-var-nginx-module/

Content of this .conf is:
#load_module modules/ngx_http_array_var_module.so;
load_module /opt/source/nginx/modules/ngx_http_array_var_module.so;

My configure is to be found on /usr/lib/nginx/nginx-1.14.0 (Download nginx source for configure).
Now i get the error message on start nginx /etc/init.d/nginx start (nginx -c /etc/nginx/nginx.conf -t):
nginx: [emerg] dlopen() "/opt/source/nginx/modules/ngx_http_array_var_module.so" failed (/opt/source/nginx/modules/ngx_http_array_var_module.so: undefined symbol: ndk_set_var_value) in /etc/nginx/modules-enabled/51-mod-http-array-var-module.conf:2
nginx: configuration file /etc/nginx/nginx.conf test failed.

What is wrong with?

Sorry, this is the first time for me with working nginx modules.

**Comment by pet21221** [comment]
Sorry, it's the first time for me with working nginx & nginx modules. 
Now i configured it with ngx_devel_kit.

Before i want to install this module, i installed nginx with apt-get install nginx (/etc/nginx/). But there was no ./configure and i get on /usr/lib/nginx/nginx-1.14.0 the nginx source for configurate.
In this folder i run:
1. ./configure --prefix=/opt/source/nginx --add-dynamic-module=/opt/source/nginx/ngx_devel_kit --add-dynamic-module=/opt/source/nginx/array-var-nginx-module/
2. make -j2
3. make install

Now i could find both modules on /opt/source/nginx/modules/. I create on my already exists /etc/nginx/modules-enabled/ this .conf file: 51-mod-http-array-var-module.conf with the following content:
`#load_module modules/ngx_http_array_var_module.so;
load_module /opt/source/nginx/modules/ndk_http_module.so;
load_module /opt/source/nginx/modules/ngx_http_array_var_module.so;`

But on start nginx (etc/init.d/nginx start) i could an error. 
I check it with nginx -c /etc/nginx/nginx.conf -t.
I get this back:
`nginx: [emerg] module "/opt/source/nginx/modules/ndk_http_module.so" is not binary compatible in /etc/nginx/modules-enabled/51-mod-http-array-var-module.conf:2
nginx: configuration file /etc/nginx/nginx.conf test failed`

**Comment by agentzh** [comment]
@pet21221 Your Ubuntu's nginx was definitely built with a different `./configure` command line, that's why your `.so` is not compatible.
